# -*- coding: utf-8 -*-
"""CreateVideothumbnail .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3F1EuWE7ZTRJoTGQVBRV8ZjsQq0PC1t
"""

!pip install transformers accelerate torch pillow opencv-python --quiet

import cv2
import torch
from PIL import Image
import yt_dlp
from transformers import MllamaForConditionalGeneration, MllamaProcessor
from google.colab import files
from huggingface_hub import login
from IPython.display import display

login("")

def get_video_stream_path(video_input: str) -> str:
    """
    Checks if the input string is a YouTube URL.
    If true, extracts and returns the direct streaming URL via yt-dlp.
    Otherwise, returns the original local path string.
    """
    if "youtube.com" in video_input or "youtu.be" in video_input:
        print("📺 YouTube link detected. Extracting direct stream URL...")
        ydl_opts = {
            'format': 'bestvideo[ext=mp4]/mp4',
            'quiet': True,
            'no_warnings': True
        }
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_input, download=False)
            return info['url']
    else:
        print("📂 Local path detected. Proceeding with file path...")
        return video_input

def extract_candidate_frames(video_input: str, num_candidates: int = 3) -> dict:
    """Extracts evenly spaced frames from a local video file or a YouTube stream link."""
    resolved_path = get_video_stream_path(video_input)

    cap = cv2.VideoCapture(resolved_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    # Workaround fallback if stream metadata doesn't initially expose a total frame count
    if total_frames <= 0:
        total_frames = int(fps * 45) if fps > 0 else 1200

    interval = total_frames // (num_candidates + 1)
    candidates = {}

    for i in range(1, num_candidates + 1):
        frame_idx = i * interval
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ret, frame = cap.read()
        if ret:
            # Convert OpenCV BGR channel mapping to standard PIL RGB format
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            pil_img = Image.fromarray(rgb_frame)
            candidates[i] = {"image": pil_img, "frame_idx": frame_idx}
        else:
            print(f"⚠️ Unable to parse frames around position index: {frame_idx}")

    cap.release()

    if not candidates:
        raise ValueError("Could not successfully capture any target video frames.")

    return candidates

def pick_best_thumbnail_with_llama(video_path: str):
    # 1. Trigger the user authentication prompt for HuggingFace Hub access
    print("--- Hugging Face Authentication ---")
    login()

    # 2. Slice candidates from the source video path
    candidates = extract_candidate_frames(video_path, num_candidates=3)

    # 3. Load Llama 3.2 Vision Model weights onto the T4 GPU
    print("\n🚀 Initializing Meta-Llama-3.2-11B-Vision-Instruct...")
    model_id = "meta-llama/Llama-3.2-11B-Vision-Instruct"

    model = MllamaForConditionalGeneration.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16,   # Fits cleanly into Colab T4's 16GB VRAM bounds
        device_map="auto"
    )
    processor = MllamaProcessor.from_pretrained(model_id)

    # 4. Prompt structuring engineering for Visual Context evaluation
    prompt_text = (
        "You are an expert YouTube thumbnail designer. Look at these 3 frames sampled from a video. "
        "Analyze their lighting, composition, and subject matter. Tell me which frame (1, 2, or 3) "
        "would make the most compelling, high-click-through-rate thumbnail. "
        "Start your response strictly with: 'CHOSEN FRAME: [Number]' followed by a brief 2-sentence explanation."
    )

    conversation = [
        {
            "role": "user",
            "content": [
                {"type": "image"}, # Frame 1
                {"type": "image"}, # Frame 2
                {"type": "image"}, # Frame 3
                {"type": "text", "text": prompt_text}
            ]
        }
    ]

    images = [candidates[1]["image"], candidates[2]["image"], candidates[3]["image"]]
    prompt = processor.apply_chat_template(conversation, add_generation_prompt=True, tokenize=False)
    inputs = processor(prompt, images, return_tensors="pt").to(model.device)

    print("🧠 Llama is evaluating visual features and CTR potential...")
    output = model.generate(**inputs, max_new_tokens=150)
    response = processor.decode(output[0])[len(prompt):]

    print("\n🎬 --- Llama's Editorial Decision ---")
    print(response.strip())

    # 5. Extract structural selection numerical identity value
    chosen_idx = 1
    for num in ["1", "2", "3"]:
        if f"CHOSEN FRAME: {num}" in response or f"FRAME: {num}" in response:
            chosen_idx = int(num)
            break

    # 6. Isolate and cache selected image asset path output
    final_thumbnail = candidates[chosen_idx]["image"]
    output_filename = "chosen_thumbnail.png"
    final_thumbnail.save(output_filename)
    print(f"\n✨ Successfully captured and saved Frame {chosen_idx} as '{output_filename}'!")

    print("\n--- Displaying Selection ---")
    display(final_thumbnail)
    return final_thumbnail

# --- Execution Entry Point ---
if __name__ == "__main__":
    # You can alternate this directly with a local file path (e.g. "my_video.mp4")
    # or keep a YouTube URL string here.

    target_video_path = "/content/sample_data/14351124_3840_2160_60fps.mp4"

    # Run the full automation stack
    best_frame = pick_best_thumbnail_with_llama(target_video_path)

import cv2
import torch
from PIL import Image
from transformers import MllamaForConditionalGeneration, MllamaProcessor
from google.colab import files
from huggingface_hub import login

# 1. Authenticate with Hugging Face
# (Paste your token when prompted, or pass it directly: login("your_token_here"))


login("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")

def extract_candidate_frames(video_path, num_candidates=5):
    """Extracts evenly spaced frames from the video to analyze."""
    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    if total_frames == 0:
        raise ValueError("Could not read the video file.")

    interval = total_frames // (num_candidates + 1)
    candidates = {}

    for i in range(1, num_candidates + 1):
        frame_idx = i * interval
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ret, frame = cap.read()
        if ret:
            # Convert OpenCV BGR to PIL RGB
            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            pil_img = Image.fromarray(rgb_frame)
            timestamp_sec = frame_idx / fps
            candidates[i] = {"image": pil_img, "timestamp": timestamp_sec, "frame_idx": frame_idx}

    cap.release()
    return candidates

def pick_best_thumbnail_with_llama(video_path):
    # Load candidate frames
    print("Extracting candidate frames from video...")
    candidates = extract_candidate_frames(video_path, num_candidates=3)

    # Load Llama 3.2 Vision Model (using bfloat16 to fit nicely in Colab's T4 GPU memory)
    print("Loading Meta-Llama-3.2-11B-Vision...")
    model_id = "meta-llama/Llama-3.2-11B-Vision-Instruct"

    model = MllamaForConditionalGeneration.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16,
        device_map="auto"
    )
    processor = MllamaProcessor.from_pretrained(model_id)

    # Formulate a structured prompt asking Llama to act as a media editor
    prompt_text = (
        "You are an expert YouTube thumbnail designer. Look at these 3 frames sampled from a video. "
        "Analyze their lighting, composition, and subject matter. Tell me which frame (1, 2, or 3) "
        "would make the most compelling, high-click-through-rate thumbnail. "
        "Start your response strictly with: 'CHOSEN FRAME: [Number]' followed by a brief 2-sentence explanation."
    )

    conversation = [
        {
            "role": "user",
            "content": [
                {"type": "image"}, # Frame 1
                {"type": "image"}, # Frame 2
                {"type": "image"}, # Frame 3
                {"type": "text", "text": prompt_text}
            ]
        }
    ]

    # Process inputs
    images = [candidates[1]["image"], candidates[2]["image"], candidates[3]["image"]]
    prompt = processor.apply_chat_template(conversation, add_generation_prompt=True, tokenize=False)
    inputs = processor(prompt, images, return_tensors="pt").to(model.device)

    print("Llama is analyzing the frames...")
    output = model.generate(**inputs, max_new_tokens=150)
    response = processor.decode(output[0])[len(prompt):]

    print("\n--- Llama's Editorial Decision ---")
    print(response.strip())

    # Basic parsing logic to figure out what Llama picked
    chosen_idx = 1 # fallback default
    for num in ["1", "2", "3"]:
        if f"CHOSEN FRAME: {num}" in response or f"FRAME: {num}" in response:
            chosen_idx = int(num)
            break

    # Save the winner
    final_thumbnail = candidates[chosen_idx]["image"]
    final_thumbnail.save("chosen_thumbnail.png")
    print(f"\nSaved Frame {chosen_idx} as 'chosen_thumbnail.png'!")

    return final_thumbnail

# --- Execution ---
# Upload a short test video (.mp4) to your Colab environment files sidebar,
# rename the variable below to match your video filename, and run it!
video_filename = "sample_data/14351124_3840_2160_60fps.mp4"
best_frame = pick_best_thumbnail_with_llama(video_filename)
best_frame

from google.colab import drive
drive.mount('/content/drive')